steps: 
    # 1. Run secret detection with gitleaks
    - name: 'zricethezav/gitleaks:latest'
      entrypoint: 'sh'
      args: 
        - '-c'
        - git config --global --add safe.directory /workspace && gitleaks detect --source=/workspace --verbose --redact

    # 2. Run filesystem vulnerability scan with trivy
    - name: 'aquasec/trivy:latest'
      args: 
        - 'fs'
        - '--exit-code'
        - '1'
        - '--severity'
        - 'CRITICAL,HIGH'
        - '/workspace'

    # 3. Build Docker container image 
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'build'
        - '-t'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend-api:$COMMIT_SHA'
        - '-t'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend-api:latest'
        - './src'

    # 4. scan container image with trivy before pushing 
    - name: 'aquasec/trivy:latest'
      args:
        - 'image'
        - '--exit-code'
        - '1'
        - '--severity'
        - 'CRITICAL'
        - '--ignore-unfixed'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend-api:$COMMIT_SHA'

    # 5. Push validated image to google arrtifact registry
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'push'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend-api:$COMMIT_SHA'
#6 step
    - name: 'gcr.io/cloud-builders/docker'
      args:
        -  'push'
        -  '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend-api:latest'
#7 step
    - name: 'gcr.io/cloud-builders/git'
      id: 'UPDATE-GITOPS-MANIFEST'
      entrypoint: 'bash'
      secretEnv:
        - 'GITHUB_TOKEN'
      env:
        - 'PROJECT_ID=$PROJECT_ID'
        - 'COMMIT_SHA=$COMMIT_SHA'
      args:
        - '-c'
        - |
            chmod +x scripts/update-image.sh
            ./scripts/update-image.sh  
#8 step
    - name: 'gcr.io/cloud-builders/kubectl'
      id: 'CONFIGURE-GKE'
      env: 
        - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
        - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
        - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      args:
        - 'get'
        - 'nodes'
# create namespace for argocd
    - name: 'gcr.io/cloud-builders/kubectl'
      id: 'CREATE-NAMESPACE-ARGOCD'
      entrypoint: 'bash'
      env: 
        - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
        - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
        - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      args:
         -  '-c'
         - 'kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -'
  # 9. Install Argo CD and create Argo CD Application

    - name: 'gcr.io/cloud-builders/kubectl'

      id: 'INSTALL-ARGOCD'
      env: 
        - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
        - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
        - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      args:
         -  'apply'
         - '-n'
         - 'argocd'
         - '--server-side'
         - '--force-conflicts'
         - '-f'
         - 'https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml'  
#step 10 wait for ARGO CD server 
    - name: 'gcr.io/cloud-builders/kubectl'
      id: 'WAIT-FOR-ARGOCD-SERVER'
      env: 
        - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
        - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
        - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      entrypoint: 'bash'
      args:
         -  '-c'
         -  |
               echo "Checking Argo CD resources..."
               kubectl get namespace argocd
               kubectl get deployments -n argocd
               kubectl get pods -n argocd
               echo "Waiting for argocd-server deployment to appear..."
               for i in {1..30}; do
                 if kubectl get deployment argocd-server -n argocd >/dev/null 2>&1; then
                   echo "argocd-server deployment found."  
                   break
                 fi
                 echo "argocd-server not found yet. Waiting 10 seconds..."
                 sleep 10
                done
                kubectl get deployment argocd-server -n argocd
                kubectl wait \
                  --for=condition=available \
                  deployment/argocd-server \
                  -n argocd \
                 --timeout=300s

# step 11 create ARGO CD application
    - name: 'gcr.io/cloud-builders/kubectl'
      id: 'CREATE-ARGOCD-APPLICATION'
      env: 
        - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
        - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
        - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      args:
         -  'apply'
         -  '-f'
         -  'k8s/overlays/argocd-application.yaml'  

# step 12 verify ARGO CD application 
    - name: 'gcr.io/cloud-builders/kubectl'
      id: 'VERIFY-ARGOCD-APPLICATION'
      env: 
        - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
        - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
        - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      args:
         -  'get'
         -  'applications'
         - '-A'       

substitutions:
    _REGION: 'us-central1'
    _REPO_NAME: 'app-practice-artifact-repo' 
    _CLUSTER_NAME: 'practice-gke-cluster' 

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/jenkins-cicd@gke-project-1-500610.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/GitHub-token/versions/latest'
      env: 'GITHUB_TOKEN'

