apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: gke-workload-identity-sa@gke-project-1-500610.iam.gserviceaccount.com
